### ISSUE TITLE
Autocrafting table does not consume resources consistently 

### ISSUE THREAD

**Issue by tofuninja** [SytxLabs/MCAutoCrafter#4]
During one test of mine I set up a table to craft torches. Put in a full stack of coal and sticks into dispenser and activated it and it did produce 4 torches but it consumed all the coal and sticks. 

Then I tried again with 3 coal and 3 sticks after remaking the autocrafter and this time it sometimes didn't consume any of the resources so that I was able to get 20 torches when it should have only produced 12. And there was one coal left over for some reason. 

I am running a server from a hosting service so I duno if it might be a source of inconsistency.

**Comment by shaunluedeke** [comment]
i think i know where the bug is i'll have a look at it

**Comment by tofuninja** [comment]
Something I just noticed now in my server logs

[09:01:48 INFO]: [AutoCrafter] There is a new update available (1.2.3): https://www.spigotmc.org/resources/autocrafter.113127/

But I grab the latest jar from spigotmc.org so I am not really sure why it is still saying 1.2.2

(also thanks for the quick response ya doing awesome work)

**Comment by shaunluedeke** [comment]
will be fixed later with the other fix

**Comment by shaunluedeke** [comment]
Ich hab grade ein Fix geschrieben muss ich später nurnoch einmal testen

**Comment by shaunluedeke** [comment]
I have just written a fix, I just have to test it later

**Comment by shaunluedeke** [comment]
The new version is on SpigotMC https://www.spigotmc.org/resources/autocrafter.113127/ . Sry for this bug :D
