### ISSUE TITLE
Error in Minecraft version 1.20.4

### ISSUE THREAD

**Issue by Lele289** [SytxLabs/MCAutoCrafter#6]
![image](https://github.com/SytxLabs/MCAutoCrafter/assets/91186497/3f56467e-0d46-466b-90ec-00486a634f4c)
I have this version error, when I start the server in 1.20.4, but when I start the server in 1.20.2 everything works fine, so the plugin in minecraft 1.20.4 cannot be started

**Comment by shaunluedeke** [comment]
hello which plugin version did you use?

**Comment by Lele289** [comment]
1.2.4

**Comment by shaunluedeke** [comment]
Unfortunately I could not reproduce the error try to delete your crafter.yml and check if you have the latest version

**Comment by Lele289** [comment]
I solved it by deleting the crafting.yml file and the other files in the folder and reconfiguring everything, thanks for the support
